update empresabds set email='franciscobarroso@entetecnologia.com.br';
update candidato set email='franciscobarroso@entetecnologia.com.br';
update colaborador set email='franciscobarroso@entetecnologia.com.br';
update parametrosdosistema set emailUser='franciscobarroso@entetecnologia.com.br';
update empresa set emailRemetente='franciscobarroso@entetecnologia.com.br';
update empresa set emailRespSetorPessoal='franciscobarroso@entetecnologia.com.br';
update empresa set emailresprh='franciscobarroso@entetecnologia.com.br';
update areaorganizacional set emailsnotificacoes = null;
update usuario set senha='MTIzNA==';
update historicocolaborador set salario=5555.00;
update gastoempresaitem set valor=25.00;
update historicobeneficio set valor=55.00;
update parametrosdosistema set enviaremail=false;
update empresa set acintegra=false;