package com.fortes.rh.test.selenium.smoke;

import static com.fortes.rh.test.AbstractSeleniumSuite.getAppUrl;
import static com.fortes.rh.test.AbstractSeleniumSuite.getSeleniumInstance;
import static com.fortes.rh.test.AbstractSeleniumSuite.verificaLogin;
import junit.framework.TestCase;

import com.thoughtworks.selenium.Selenium;

public class TesteSeleniumMenu extends TestCase
{
	private Selenium selenium;

	public TesteSeleniumMenu()
	{
		selenium = getSeleniumInstance();
	}

	public void testMenu() throws Exception
	{
		selenium.open(getAppUrl());
		verificaLogin();

		selenium.open(getAppUrl() + "/fortesrh/index.action");
		selenium.click("//div[@id='logoDiv']/a/img");
		selenium.waitForPageToLoad("30000");
		assertTrue(selenium.getTitle().equals("Fortes RH"));
		
		selenium.click("link=Candidatos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Candidatos", selenium.getTitle());
		selenium.click("link=Etapas Seletivas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Etapas Seletivas", selenium.getTitle());
		selenium.click("link=Empresas BDS");
		selenium.waitForPageToLoad("30000");
		assertEquals("Empresas BDS (Banco de Dados Solidário)", selenium.getTitle());
		selenium.click("link=Áreas de Interesse");
		selenium.waitForPageToLoad("30000");
		assertEquals("Áreas de Interesse", selenium.getTitle());
		selenium.click("link=Áreas de Formação");
		selenium.waitForPageToLoad("30000");
		assertEquals("Áreas de Formação", selenium.getTitle());
		selenium.click("link=Motivos de Solicitação de Pessoal");
		selenium.waitForPageToLoad("30000");
		assertEquals("Motivos de Solicitação", selenium.getTitle());
		selenium.click("link=Solicitação de Pessoal");
		selenium.waitForPageToLoad("30000");
		assertEquals("Solicitações de Pessoal", selenium.getTitle());
		assertEquals("Solicitações de Pessoal", selenium.getTitle());
		selenium.click("link=Solicitações Abertas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Solicitações Abertas", selenium.getTitle());
		selenium.click("link=Processos Seletivos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Processos Seletivos", selenium.getTitle());
		selenium.click("link=Avaliações de Candidatos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Avaliações de Candidatos", selenium.getTitle());
		selenium.click("link=Áreas Organizacionais");
		selenium.waitForPageToLoad("30000");
		assertEquals("Áreas Organizacionais", selenium.getTitle());
		selenium.click("link=Grupos Ocupacionais");
		selenium.waitForPageToLoad("30000");
		assertEquals("Grupos Ocupacionais", selenium.getTitle());
		selenium.click("link=Conhecimentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Conhecimentos", selenium.getTitle());
		selenium.click("link=Cargos e Faixas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Cargos", selenium.getTitle());
		selenium.click("link=Índices");
		selenium.waitForPageToLoad("30000");
		assertEquals("Índices", selenium.getTitle());
		selenium.click("link=Planejamentos de Realinhamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Planejamentos de Realinhamentos", selenium.getTitle());
		selenium.click("link=Solicitação de Realinhamento de C&S");
		selenium.waitForPageToLoad("30000");
		assertEquals("Solicitação de Realinhamento de Cargos & Salários", selenium.getTitle());
		selenium.click("link=Reajuste Coletivo");
		selenium.waitForPageToLoad("30000");
		assertEquals("Reajuste Coletivo/Dissídio", selenium.getTitle());
		selenium.click("link=Cargos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Cargos", selenium.getTitle());
		selenium.click("link=Realinhamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Simulação de Realinhamentos", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[8]/ul/li[3]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Áreas Organizacionais", selenium.getTitle());
		selenium.click("link=Análise de Tabela Salarial");
		selenium.waitForPageToLoad("30000");
		assertEquals("Análise de Tabela Salarial", selenium.getTitle());
		selenium.click("link=Projeção Salarial");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Projeção Salarial", selenium.getTitle());
		selenium.click("//a[contains(text(),'Pesquisas')]");
		selenium.waitForPageToLoad("30000");
		assertEquals("Pesquisas", selenium.getTitle());
		selenium.click("link=Prioridades de Treinamento");
		selenium.waitForPageToLoad("30000");
		assertEquals("Prioridades de Treinamentos", selenium.getTitle());
		selenium.click("link=Cursos/Treinamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Cursos", selenium.getTitle());
		selenium.click("link=Avaliações dos Cursos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Avaliacões dos Cursos", selenium.getTitle());
		selenium.click("link=Modelos de Avaliação de Curso");
		selenium.waitForPageToLoad("30000");
		assertEquals("Modelos de Avaliação de Curso", selenium.getTitle());
		selenium.click("link=Certificações");
		selenium.waitForPageToLoad("30000");
		assertEquals("Certificações", selenium.getTitle());
		selenium.click("link=DNT");
		selenium.waitForPageToLoad("30000");
		assertEquals("DNT - Diagnóstico de Necessidade de Treinamento", selenium.getTitle());
		selenium.click("link=Preenchimento da DNT");
		selenium.waitForPageToLoad("30000");
		assertEquals("DNT - Colaborador X Curso X Prioridade", selenium.getTitle());
		selenium.click("link=Frequência");
		selenium.waitForPageToLoad("30000");
		assertEquals("Controle de Freqüência", selenium.getTitle());
		selenium.click("link=Plano de Treinamento");
		selenium.waitForPageToLoad("30000");
		assertEquals("Plano de Treinamento", selenium.getTitle());
		selenium.click("link=Matriz de Qualificação");
		selenium.waitForPageToLoad("30000");
		assertEquals("Matriz de Qualificação", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[16]/ul/li[2]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Plano de Treinamentos", selenium.getTitle());
		selenium.click("link=Colaboradores sem Indicação de Trein.");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Colaboradores Sem Indicação de Treinamento", selenium.getTitle());
		selenium.click("link=Lista de Frequência");
		selenium.waitForPageToLoad("30000");
		assertEquals("Lista de Freqüência", selenium.getTitle());
		selenium.click("link=Certificados");
		selenium.waitForPageToLoad("30000");
		assertEquals("Impressão de Certificado", selenium.getTitle());
		selenium.click("link=Cronograma de Treinamento");
		selenium.waitForPageToLoad("30000");
		assertEquals("Cronograma de treinamento", selenium.getTitle());
		selenium.click("link=Colaboradores sem Treinamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de colaboradores que não fizeram um treinamento", selenium.getTitle());
		selenium.click("link=Colaboradores com Treinamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de colaboradores que fizeram um treinamento", selenium.getTitle());
		selenium.click("link=Matriz de Treinamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Matriz de Treinamento", selenium.getTitle());
		selenium.click("link=Histórico de Treinamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Histórico de Treinamentos por Colaborador", selenium.getTitle());
		selenium.click("link=Painel de Indicadores");
		selenium.waitForPageToLoad("30000");
		assertEquals("Painel de Indicadores de T&D", selenium.getTitle());
		selenium.click("link=Grupos de Investimento");
		selenium.waitForPageToLoad("30000");
		assertEquals("Grupos de Investimentos", selenium.getTitle());
		selenium.click("link=Investimentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Investimentos", selenium.getTitle());
		selenium.click("link=Benefícios");
		selenium.waitForPageToLoad("30000");
		assertEquals("Benefícios", selenium.getTitle());
		selenium.click("link=Motivos de Desligamento");
		selenium.waitForPageToLoad("30000");
		assertEquals("Motivos de Desligamento", selenium.getTitle());
		selenium.click("link=Modelos de Entrevistas de Desligamento");
		selenium.waitForPageToLoad("30000");
		assertEquals("Modelos de Entrevistas de Desligamento", selenium.getTitle());
		selenium.click("link=Ocorrências");
		selenium.waitForPageToLoad("30000");
		assertEquals("Ocorrências", selenium.getTitle());
		selenium.click("link=Colaboradores");
		selenium.waitForPageToLoad("30000");
		assertEquals("Colaboradores", selenium.getTitle());
		selenium.click("link=Atualizar meus dados");
		selenium.waitForPageToLoad("30000");
		assertEquals("Editar Informações Pessoais", selenium.getTitle());
		selenium.click("link=Investimentos da Empresa");
		selenium.open(getAppUrl() + "/geral/gastoEmpresa/list.action");
		selenium.waitForPageToLoad("30000");
		assertEquals("Investimentos da Empresa - por Colaborador", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[20]/ul/li[1]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Ocorrências", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[20]/ul/li[2]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Motivos de Desligamento", selenium.getTitle());
		selenium.click("link=Resultados das Entrevistas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Gerar Resultado da Entrevista", selenium.getTitle());
		selenium.click("link=Aniversariantes do mês");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório - Aniversariantes do mês", selenium.getTitle());
		selenium.click("link=Estatísticas de Vagas por Motivo");
		selenium.waitForPageToLoad("30000");
		assertEquals("Recrutamento e Seleção - Estatísticas de Vagas por Motivo", selenium.getTitle());
		selenium.click("link=Duração para Preenchimento de Vagas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Recrutamento e Seleção - Duração para Preenchimento de Vaga", selenium.getTitle());
		selenium.click("link=Produtividade do Setor");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Produtividade do Setor", selenium.getTitle());
		selenium.click("link=Promoções");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Promoções", selenium.getTitle());
		selenium.click("link=Turnover (rotatividade)");
		selenium.waitForPageToLoad("30000");
		assertEquals("Turnover (rotatividade de colaboradores)", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[22]/ul/li[6]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Investimentos da Empresa", selenium.getTitle());
		selenium.click("link=Tipos de EPI");
		selenium.waitForPageToLoad("30000");
		assertEquals("Tipos de EPI", selenium.getTitle());
		selenium.click("link=EPI");
		selenium.waitForPageToLoad("30000");
		assertEquals("EPIs", selenium.getTitle());
		selenium.click("link=EPC");
		selenium.waitForPageToLoad("30000");
		assertEquals("EPCs", selenium.getTitle());
		selenium.click("link=Riscos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Riscos", selenium.getTitle());
		selenium.click("link=Ambientes");
		selenium.waitForPageToLoad("30000");
		assertEquals("Ambientes", selenium.getTitle());
		selenium.click("link=Engenheiros Responsáveis");
		selenium.waitForPageToLoad("30000");
		assertEquals("Engenheiros Responsáveis do Trabalho", selenium.getTitle());
		selenium.click("link=Extintores");
		selenium.waitForPageToLoad("30000");
		assertEquals("Extintores", selenium.getTitle());
		selenium.click("link=Etapas do Processo Eleitoral");
		selenium.waitForPageToLoad("30000");
		assertEquals("CIPA - Etapas do Processo Eleitoral", selenium.getTitle());
		selenium.click("link=Eleições");
		selenium.waitForPageToLoad("30000");
		assertEquals("Eleicões", selenium.getTitle());
		selenium.click("link=Comissões");
		selenium.waitForPageToLoad("30000");
		assertEquals("Comissões", selenium.getTitle());
		selenium.click("link=Eventos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Eventos", selenium.getTitle());
		selenium.click("link=Agenda");
		selenium.waitForPageToLoad("30000");
		assertEquals("Agenda", selenium.getTitle());
		selenium.click("link=Exames");
		selenium.waitForPageToLoad("30000");
		assertEquals("Exames", selenium.getTitle());
		selenium.click("link=Médicos Coordenadores");
		selenium.waitForPageToLoad("30000");
		assertEquals("Médicos Coordenadores", selenium.getTitle());
		selenium.click("link=Clínicas e Médicos Autorizados");
		selenium.waitForPageToLoad("30000");
		assertEquals("Clínicas e Médicos Autorizados", selenium.getTitle());
		selenium.click("link=Modelos de Fichas Médicas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Modelos de Fichas Médicas", selenium.getTitle());
		selenium.click("link=Tipos de Afastamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Tipos de Afastamento", selenium.getTitle());
		selenium.click("link=Medição dos Riscos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Medição dos Riscos", selenium.getTitle());
		selenium.click("link=Solicitação de EPIs");
		selenium.waitForPageToLoad("30000");
		assertEquals("Solicitações de EPI", selenium.getTitle());
		selenium.click("link=Entrega de EPIs");
		selenium.waitForPageToLoad("30000");
		assertEquals("Solicitações de EPI", selenium.getTitle());
		selenium.click("link=Inspeção");
		selenium.waitForPageToLoad("30000");
		assertEquals("Extintores - Inspeção", selenium.getTitle());
		selenium.open(getAppUrl() + "/sesmt/extintorManutencao/list.action");
		selenium.waitForPageToLoad("30000");
		assertEquals("Extintores - Manutenção", selenium.getTitle());
		selenium.open(getAppUrl() + "/sesmt/solicitacaoExame/list.action");
		selenium.waitForPageToLoad("30000");
		assertEquals("Solicitações/Atendimentos Médicos", selenium.getTitle());
		selenium.click("link=Mudança de Função");
		selenium.waitForPageToLoad("30000");
		assertEquals("Mudança de Função", selenium.getTitle());
		selenium.click("link=Registro de Prontuário");
		selenium.waitForPageToLoad("30000");
		assertEquals("Registros de Prontuários", selenium.getTitle());
		selenium.click("link=Fichas Médicas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Fichas Médicas", selenium.getTitle());
		selenium.click("link=Afastamentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Afastamentos", selenium.getTitle());
		selenium.click("link=CATs (Acidentes de Trabalho)");
		selenium.waitForPageToLoad("30000");
		assertEquals("CAT - Comunicação de Acidente de Trabalho", selenium.getTitle());
		selenium.click("link=PPRA e LTCAT");
		selenium.waitForPageToLoad("30000");
		assertEquals("PPRA e LTCAT", selenium.getTitle());
		selenium.click("link=PPP");
		selenium.waitForPageToLoad("30000");
		assertEquals("Lista de Colaboradores", selenium.getTitle());
		selenium.click("link=Ficha de EPI");
		selenium.waitForPageToLoad("30000");
		assertEquals("Ficha de EPI", selenium.getTitle());
		selenium.click("link=EPIs com CA a Vencer");
		selenium.waitForPageToLoad("30000");
		assertEquals("EPIs com CA a Vencer", selenium.getTitle());
		selenium.click("link=EPIs com Prazo a Vencer");
		selenium.waitForPageToLoad("30000");
		assertEquals("EPIs com Prazo a Vencer", selenium.getTitle());
		selenium.click("link=Extintores - Manutenção e Inspeção");
		selenium.waitForPageToLoad("30000");
		assertEquals("Extintores - Manutenção e Inspeção", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[29]/ul/li[7]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("PCMSO", selenium.getTitle());
		selenium.click("link=Prontuário");
		selenium.waitForPageToLoad("30000");
		assertEquals("Prontuário", selenium.getTitle());
		selenium.click("link=ASOs");
		selenium.waitForPageToLoad("30000");
		assertEquals("ASOs", selenium.getTitle());
		selenium.click("link=Exames Previstos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Exames Previstos", selenium.getTitle());
		selenium.click("//div[@id='subMenusContainer']/div[29]/ul/li[11]/a");
		selenium.waitForPageToLoad("30000");
		assertEquals("Relatório de Afastamentos", selenium.getTitle());
		selenium.click("link=Resultado de Fichas Médicas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Gerar Resultado da Ficha médica", selenium.getTitle());
		selenium.click("link=Empresas");
		selenium.waitForPageToLoad("30000");
		assertEquals("Empresas", selenium.getTitle());
		selenium.click("link=Perfis");
		selenium.waitForPageToLoad("30000");
		assertEquals("Perfis", selenium.getTitle());
		selenium.click("link=Estabelecimentos");
		selenium.waitForPageToLoad("30000");
		assertEquals("Cadastro de Estabelecimentos", selenium.getTitle());
		selenium.click("link=Usuários");
		selenium.waitForPageToLoad("30000");
		assertEquals("Usuários", selenium.getTitle());
		selenium.click("link=Bairros");
		selenium.waitForPageToLoad("30000");
		assertEquals("Bairros", selenium.getTitle());
		selenium.click("link=Alterar Senha");
		selenium.waitForPageToLoad("30000");
		assertEquals("Alterar senha de Usuário", selenium.getTitle());
		selenium.click("link=Configurações");
		selenium.waitForPageToLoad("30000");
		assertEquals("Editar Pârametros do Sistema", selenium.getTitle());
		selenium.click("link=Auditoria");
		selenium.waitForPageToLoad("30000");
		assertEquals("Auditoria do Sistema", selenium.getTitle());
		selenium.click("link=Histórico de Versões");
		selenium.waitForPageToLoad("30000");
		assertEquals("Documento de Versão", selenium.getTitle());
		selenium.click("link=Enviar Mensagem");
		selenium.waitForPageToLoad("30000");
		assertEquals("Enviar Mensagem", selenium.getTitle());
		selenium.click("link=Logs");
		selenium.waitForPageToLoad("30000");
		assertEquals("Arquivos de Log", selenium.getTitle());
		selenium.click("link=Sair");
		selenium.waitForPageToLoad("30000");
		assertEquals("Login", selenium.getTitle());
	}
}