package com.fortes.rh.model.dicionario;

import java.util.LinkedHashMap;

@SuppressWarnings("serial")
public class Entidade extends LinkedHashMap<String, String> {
	
	public Entidade() 
	{
		put("afastamento", "afastamento");
		put("agenda", "agenda");
		put("ambiente", "ambiente");
		put("anexo", "anexo");
		put("anuncio", "anúncio");
		put("aproveitamentoavaliacaocurso", "aproveitamento de avaliação de aluno");
		put("areaformacao", "área de formação");
		put("areainteresse", "área de interesse");
		put("areainteresse_areaorganizacional", "áreas de interesse da área organizacional");
		put("areaorganizacional", "área organizacional");
		put("areavivencia", "área de vivência");
		put("areavivenciapcmat", "áreas de vivência do PCMAT");
		put("aspecto", "aspecto");
		put("atitude", "atitude");
		put("atitude_areaorganizacional", "atitudes da área organizacional");
		put("atitude_curso", "atitudes do curso");
		put("atividadesegurancapcmat", "atividades de segurança do PCMAT");
		put("auditoria", "auditoria");
		put("avaliacao", "avaliação");
		put("avaliacaocurso", "avaliação de aluno");
		put("avaliacaodesempenho", "avaliação de desempenho");
		put("avaliacaoturma", "modelo de avaliação de curso");
		put("bairro", "bairro");
		put("beneficio", "benefício");
		put("camposextras", "campos extras");
		put("candidato", "candidato");
		put("candidato_areainteresse", "áreas de interesse do candidato");
		put("candidato_cargo", "cargos do candidato");
		put("candidato_conhecimento", "conhecimentos do candidato");
		put("candidatocurriculo", "currículos do candidato");
		put("candidatoeleicao", "candidatos da eleição");
		put("candidatoidioma", "idiomas do candidato");
		put("candidatosolicitacao", "candidatos da solicitação");
		put("cargo", "cargo");
		put("cargo_areaformacao", "áreas de formação do cargo");
		put("cargo_areaorganizacional", "áreas organizacionais do cargo");
		put("cargo_atitude", "atitudes do cargo");
		put("cargo_conhecimento", "conhecimentos do cargo");
		put("cargo_etapaseletiva", "etapas seletivas do cargo");
		put("cargo_habilidade", "habilidades do cargo");
		put("cat", "CAT");
		put("cat_epi", "EPIs do CAT");
		put("certificacao", "certificação");
		put("certificacao_curso", "cursos da certificação");
		put("cid", "CID");
		put("cidade", "cidade");
		put("cliente", "cliente");
		put("clinicaautorizada", "clínica autorizada");
		put("clinicaautorizada_exame", "exames da clínica autorizada");
		put("codigocbo", "CBO");
		put("colaborador", "colaborador");
		put("colaboradorafastamento", "afastamentos do colaborador");
		put("colaboradoridioma", "idiomas do colaborador");
		put("colaboradorocorrencia", "ocorrências do colaborador");
		put("colaboradorperiodoexperienciaavaliacao", "avaliações de período de experiência do colaborador");
		put("colaboradorpresenca", "presenças de curso do colaborador");
		put("colaboradorquestionario", "avaliações, entrevistas, pesquisas ou fichas médicas do colaborador");
		put("colaboradorresposta", "respostas do colaborador em avaliações, entrevistas, pesquisas ou fichas médicas");
		put("colaboradorturma", "colaboradores da turma");
		put("comissao", "comissão da CIPA");
		put("comissaoeleicao", "comissões da eleição da CIPA");
		put("comissaomembro", "membros da comissão da CIPA");
		put("comissaoperiodo", "períodos da comissão da CIPA");
		put("comissaoplanotrabalho", "planos de trabalho da comissão da CIPA");
		put("comissaoreuniao", "reuniões da comissão da CIPA");
		put("comissaoreuniaopresenca", "presenças em reuniões da comissão da CIPA");
		put("comoficousabendovaga", "como ficou sabendo da vaga");
		put("composicaosesmt", "composição do SESMT");
		put("configuracaocampoextra", "configuração de campos extras");
		put("configuracaoimpressaocurriculo", "configuração de impressão de currículo");
		put("configuracaolimitecolaborador", "configuração de limite de colaborador por cargo");
		put("configuracaonivelcompetencia", "nível de competência");
		put("configuracaonivelcompetenciacolaborador", "competência do colaborador");
		put("configuracaoperformance", "configuração de performance");
		put("configuracaorelatoriodinamico", "configuração de relatório dinâmico");
		put("conhecimento", "conhecimento");
		put("conhecimento_areaorganizacional", "áreas organizacionais do conhecimento");
		put("conhecimento_curso", "cursos sugeridos para o conhecimento");
		put("curso", "curso");
		put("curso_avaliacaocurso", "avaliações de aluno do curso");
		put("curso_empresa", "empresas compartilhadas de um curso");
		put("dependente", "dependente");
		put("diaturma", "dias previstos da turma");
		put("dnt", "DNT");
		put("documentoanexo", "documentos anexos");
		put("eleicao", "eleição");
		put("empresa", "empresa");
		put("empresabds", "empresa do BDS");
		put("engenheiroresponsavel", "engenheiro responsável");
		put("entrevista", "entrevista");
		put("epc", "EPC");
		put("epcpcmat", "EPCs do PCMAT");
		put("epi", "EPI");
		put("epihistorico", "histórico de EPI");
		put("epipcmat", "EPIs do PCMAT");
		put("estabelecimento", "estabelecimento");
		put("estado", "estado");
		put("etapaprocessoeleitoral", "etapas do processo eleitoral da CIPA");
		put("etapaseletiva", "etapa seletiva");
		put("evento", "evento");
		put("exame", "exame");
		put("examesolicitacaoexame", "exames da solicitação/atendimento médico");
		put("experiencia", "experiência");
		put("extintor", "extintor");
		put("extintorinspecao", "inspeção do extintor");
		put("extintorinspecao_extintorinspecaoitem", "ítens da inspeção do extintor");
		put("extintorinspecaoitem", "ítem de inspeção de extintor");
		put("extintormanutencao", "manutenção de extintor");
		put("extintormanutencao_extintormanutencaoservico", "serviços da manutenção do extintor");
		put("extintormanutencaoservico", "serviço de manutenção de extintor");
		put("faixasalarial", "faixa salarial");
		put("faixasalarial_certificacao", "certificações da faixa salarial");
		put("faixasalarialhistorico", "histórico de faixa salarial");
		put("fase", "fase de PCMAT");
		put("fasepcmat", "fases do PCMAT");
		put("faturamentomensal", "faturamento mensal");
		put("fichamedica", "ficha médica");
		put("formacao", "formação");
		put("funcao", "função");
		put("gasto", "gasto");
		put("gastoempresa", "gasto da empresa");
		put("gastoempresaitem", "ítens do gasto da empresa");
		put("gerenciadorcomunicacao", "gerenciador de comunicação");
		put("gerenciadorcomunicacao_usuario", "usuários configurados no gerenciador de comunicação");
		put("grupoac", "grupo AC");
		put("grupogasto", "grupo de gasto");
		put("grupoocupacional", "grupo ocupacional");
		put("habilidade", "habilidade");
		put("habilidade_areaorganizacional", "áreas organizacionais da habilidade");
		put("habilidade_curso", "cursos da habilidade");
		put("historicoambiente", "histórico de ambiente");
		put("historicoambiente_epc", "EPCs do histórico do ambiente");
		put("historicobeneficio", "histórico de benefício");
		put("historicocandidato", "etapas seletivas do candidato");
		put("historicocolaborador", "histórico do colaborador");
		put("historicocolaboradorbeneficio", "benefício de colaborador");
		put("historicocolaboradorbeneficio_beneficio", "benefícios do colaborador");
		put("historicoextintor", "histórico de extintor");
		put("historicofuncao", "histórico de função");
		put("historicofuncao_epi", "EPIs do histórico da função");
		put("historicofuncao_exame", "exames do histórico da função");
		put("idioma", "idioma");
		put("indice", "índice");
		put("indicehistorico", "histórico de índice");
		put("medicaorisco", "medição de risco");
		put("medicocoordenador", "médico coordenador");
		put("medidariscofasepcmat", "medidas de segurança dos riscos da fase do PCMAT");
		put("medidaseguranca", "medidas de segurança");
		put("mensagem", "mensagem");
		put("migrations", "atualizações de banco de dados");
		put("motivodemissao", "motivo de demissão");
		put("motivosolicitacao", "motivo da solicitação de pessoal");
		put("naturezalesao", "natureza da lesão");
		put("nivelcompetencia", "nível de competência");
		put("noticia", "notícia");
		put("obra", "obra");
		put("ocorrencia", "ocorrência");
		put("papel", "papel");
		put("parametrosdosistema", "configurações do sistema");
		put("pcmat", "PCMAT");
		put("perfil", "perfil");
		put("perfil_papel", "permissões do perfil");
		put("pergunta", "pergunta");
		put("periodoexperiencia", "período de experiência");
		put("pesquisa", "pesquisa");
		put("prioridadetreinamento", "prioridade de treinamento");
		put("prontuario", "prontuário");
		put("providencia", "providência");
		put("quantidadelimitecolaboradoresporcargo", "limite de colaboradores por cargo");
		put("questionario", "avaliação, entrevista, pesquisa ou ficha médica");
		put("reajustecolaborador", "realinhamentos de cargo e salário do colaborador");
		put("reajustefaixasalarial", "reajustes coletivos de faixa salarial");
		put("reajusteindice", "reajustes coletivos de índice");
		put("realizacaoexame", "resultado de exame");
		put("resposta", "opções de resposta de pergunta objetiva ou múltipla escolha");
		put("risco", "risco");
		put("risco_epi", "EPIs do risco");
		put("riscoambiente", "riscos do ambiente");
		put("riscofasepcmat", "riscos da fase do PCMAT");
		put("riscofuncao", "riscos da função");
		put("riscomedicaorisco", "medições do risco");
		put("sinalizacaopcmat", "sinalização do PCMAT");
		put("solicitacao", "solicitação de pessoal");
		put("solicitacao_bairro", "bairros da solicitação de pessoal");
		put("solicitacaoavaliacao", "avaliações da solicitação de pessoal");
		put("solicitacaobds", "solicitação do BDS");
		put("solicitacaobds_empresabds", "solicitações da empresa do BDS");
		put("solicitacaoepi", "solicitação de EPI");
		put("solicitacaoepi_item", "ítens da solicitação de EPI");
		put("solicitacaoepiitementrega", "entregas de ítens da solicitação de EPI");
		put("solicitacaoexame", "solicitação/atendimento médico");
		put("tabelareajustecolaborador", "planejamento de realinhamento");
		put("tipodespesa", "tipo de despesa");
		put("tipodocumento", "tipo de documento");
		put("tipoepi", "tipo de EPI/Fardamento");
		put("tamanhoepi", "tamanho de EPI/Fardamento ");
		put("tamanhoepi_tipoepi", "tamanho dos tipos de EPI/Fardamento");
		put("turma", "turma");
		put("turma_avaliacaoturma", "avaliações de curso da turma");
		put("turmatipodespesa", "despesas da turma");
		put("usuario", "usuário");
		put("usuarioempresa", "empresas do usuário");
		put("usuariomensagem", "mensagens do usuário");
		put("usuarionoticia", "notícias lidas pelo usuário");
		put("configuracaonivelcompetenciafaixasalarial", "competências da faixa salarial ");
	}
	
	public static String getDescricao(String tabela)
	{
		Entidade entidade = new Entidade();
		
		if (entidade.containsKey(tabela))
			return entidade.get(tabela);
		
		return tabela;
	}
}