ALTER TABLE estado ADD COLUMN codigoibge SMALLINT;--.go

UPDATE estado SET codigoibge = 23 WHERE id = 1;--.go
UPDATE estado SET codigoibge = 26 WHERE id = 2;--.go
UPDATE estado SET codigoibge = 24 WHERE id = 3;--.go
UPDATE estado SET codigoibge = 33 WHERE id = 4;--.go
UPDATE estado SET codigoibge = 35 WHERE id = 5;--.go
UPDATE estado SET codigoibge = 43 WHERE id = 6;--.go
UPDATE estado SET codigoibge = 31 WHERE id = 7;--.go
UPDATE estado SET codigoibge = 12 WHERE id = 8;--.go
UPDATE estado SET codigoibge = 27 WHERE id = 9;--.go
UPDATE estado SET codigoibge = 13 WHERE id = 10;--.go
UPDATE estado SET codigoibge = 16 WHERE id = 11;--.go
UPDATE estado SET codigoibge = 29 WHERE id = 12;--.go
UPDATE estado SET codigoibge = 53 WHERE id = 13;--.go
UPDATE estado SET codigoibge = 32 WHERE id = 14;--.go
UPDATE estado SET codigoibge = 52 WHERE id = 15;--.go
UPDATE estado SET codigoibge = 21 WHERE id = 16;--.go
UPDATE estado SET codigoibge = 50 WHERE id = 17;--.go
UPDATE estado SET codigoibge = 51 WHERE id = 18;--.go
UPDATE estado SET codigoibge = 15 WHERE id = 19;--.go
UPDATE estado SET codigoibge = 25 WHERE id = 20;--.go
UPDATE estado SET codigoibge = 22 WHERE id = 21;--.go
UPDATE estado SET codigoibge = 41 WHERE id = 22;--.go
UPDATE estado SET codigoibge = 11 WHERE id = 23;--.go
UPDATE estado SET codigoibge = 14 WHERE id = 24;--.go
UPDATE estado SET codigoibge = 42 WHERE id = 25;--.go
UPDATE estado SET codigoibge = 28 WHERE id = 26;--.go
UPDATE estado SET codigoibge = 17 WHERE id = 27;--.go