package com.fortes.rh.business.geral;

import java.util.Collection;

import com.fortes.business.GenericManager;
import com.fortes.rh.model.geral.Colaborador;
import com.fortes.rh.model.geral.ColaboradorPeriodoExperienciaAvaliacao;

public interface ColaboradorPeriodoExperienciaAvaliacaoManager extends GenericManager<ColaboradorPeriodoExperienciaAvaliacao>
{
	void saveConfiguracaoAvaliacaoPeriodoExperiencia(Colaborador colaborador, Collection<ColaboradorPeriodoExperienciaAvaliacao> colaboradorAvaliacoes, Collection<ColaboradorPeriodoExperienciaAvaliacao> colaboradorAvaliacoesGestor);
	void removeConfiguracaoAvaliacaoPeriodoExperiencia(Character TipoColaboradorPeriodoExperienciaAvaliacao, Long... colaboradorIds);
	Collection<ColaboradorPeriodoExperienciaAvaliacao> findByColaborador(Long colaboradorId);
	void enviaLembreteColaboradorAvaliacaoPeriodoExperienciaVencendo();
	void removeByAvaliacao(Long avaliacaoId);
	void atualizaConfiguracaoAvaliacaoPeriodoExperiencia(Colaborador colaborador, Collection<ColaboradorPeriodoExperienciaAvaliacao> colaboradorAvaliacoes, Collection<ColaboradorPeriodoExperienciaAvaliacao> colaboradorAvaliacoesGestor, Boolean removeAvGestor);
	void atualizaConfiguracaoAvaliacaoPeriodoExperienciaEmVariosColaboradores(Long[] colaboradorIds, Collection<ColaboradorPeriodoExperienciaAvaliacao> colaboradorAvaliacoes, Collection<ColaboradorPeriodoExperienciaAvaliacao> colaboradorAvaliacoesGestor);
}